### ISSUE TITLE
Stealing Code is illegal. 

### ISSUE THREAD

**Issue by CybernetiX-S3C** [weidsom/JohnTheRipper#1]
https://www.openwall.com/lists/announce/2011/07/24/2

Stealing code is illegal. Next time fork it.

https://openwall.info/wiki/john/custom-builds#Compiled-for-Android

**Comment by weidsom** [comment]
Are you dumb? This is my build, motherfucker, check this out: https://www.openwall.com/lists/john-users/2017/11/09/1

Make a Google search first your little shit!
